### PR TITLE
Bump `ai.h2o` dependencies.

### PR DESCRIPTION
**Pull request by orendain**
**Changes:**
- Update `ai.h2o.h2o-genmodel` and `ai.h2o.h2o-genmodel-ext-xgboost` from `3.32.0.2` to `3.36.1.2`.
- Update `ai.h2o.mojo2` dependencies from `2.7.7` to `2.7.8`.

### CODE REVIEW

**Comment by orendain** [comment]
Just a gentle bump @achraf-mer 😉

**Review by mwysokin — APPROVED** [review]
LGTM 🖖

**Review by achraf-mer — APPROVED** [review]
:+1:

**Review by nkpng2k — APPROVED** [review]
LGTM

**Pull request merged**
