### PR TITLE
upgrade mojo runtime version for h2oai/h2oai#15174

### PR DESCRIPTION
**Pull request by thirdwing**

### CODE REVIEW

**Comment by thirdwing** [comment]
```
[2020-04-28T01:15:55.421Z] FAILURE: Build failed with an exception.

[2020-04-28T01:15:55.421Z] 

[2020-04-28T01:15:55.421Z] * What went wrong:

[2020-04-28T01:15:55.421Z] Execution failed for task ':gcp-cloud-run:bootJar'.

[2020-04-28T01:15:55.421Z] > Could not resolve all files for configuration ':gcp-cloud-run:runtimeClasspath'.

[2020-04-28T01:15:55.421Z]    > Could not find any matches for ai.h2o.mli:h2o-genmodel-ext-klime:[1.9.115,) as no versions of ai.h2o.mli:h2o-genmodel-ext-klime are available.

[2020-04-28T01:15:55.421Z]      Required by:

[2020-04-28T01:15:55.421Z]          project :gcp-cloud-run > project :local-rest-scorer > ai.h2o:mojo2-runtime-h2o3-impl:2.4.1

[2020-04-28T01:15:55.421Z] 

[2020-04-28T01:15:55.421Z] * Try:

[2020-04-28T01:15:55.421Z] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

[2020-04-28T01:15:55.421Z] 

[2020-04-28T01:15:55.421Z] * Get more help at https://help.gradle.org

[2020-04-28T01:15:55.421Z] 
```

It still failed on `Build` stage.

Can you take a look? @mmalohlava

**Comment by nkpng2k** [comment]
@thirdwing do we want to update this pr and merge?

**Comment by thirdwing** [comment]
I think we haven't figure out how to fix this.

**Comment by thirdwing** [comment]
@mmalohlava Please take a look at this.

The building with new java runtime works fine.

We can upgrade the runtime in 1.8.7 now.

**Comment by mmalohlava** [comment]
@thirdwing Looks good, i will merge - before release of templates, i wiould like to check Petr PR.

**Pull request merged**
