### PR TITLE
Release 0.0.12

### PR DESCRIPTION
**Pull request by osery**
LTS support branch release with mojo runtime upgrade.

### CODE REVIEW

**Comment by jahodfra** [comment]
Shouldn't release version go to release branch?

**Comment by jahodfra** [comment]
@osery explained that he needs the release commit just for the release branch and its change is immediately replaced back to snapshot version.

**Comment by osery** [comment]
Thanks @jahodfra :+1:.

**Comment by mmalohlava** [comment]
thank you!

**Pull request merged**
